name: Test
on:
  push:
    branches:
      - feature/test

jobs:
  ci:
    name: CI
    steps:
      - name: HashiCorp - Setup Terraform
        run: echo hello

             

#   cd:
#     name: CD
#     environment: dev
#     needs: ci
#     env:
